apiVersion: v1
kind: Pod
metadata:
    name: nginx4
spec:
  containers:
  - name: nginx4
    image: nginx:1.14.2
    ports:
       - containerPort: 80

--- 

apiVersion: v1
kind: Pod
metadata:
    name: nginx5
spec:
  containers:
  - name: nginx5
    image: nginx:1.14.2
    ports:
       - containerPort: 80
